language: php

matrix:
  include:
    - php: 7.2
      env:
        - PREFER="--prefer-lowest"
        - BEHAT_SUITE=standalone
    - php: 7.2
      env:
        - PREFER="--prefer-lowest"
        - BEHAT_SUITE=embedded
    - php: 7.2
      env:
        - PREFER="--prefer-lowest"
        - BEHAT_SUITE=cli
    - php: 7.4
      env:
        - PREFER=""
        - BEHAT_SUITE=standalone
    - php: 7.4
      env:
        - PREFER=""
        - BEHAT_SUITE=embedded
    - php: 7.4
      env:
        - PREFER=""
        - BEHAT_SUITE=cli

before_script:
    - composer self-update
    - composer update $PREFER
    - bash tests/bin/travis_jackrabbit.sh

script:
  - vendor/bin/simple-phpunit
  - php vendor/bin/phpspec run
  - php vendor/behat/behat/bin/behat --suite=$BEHAT_SUITE
